FROM python:3.8.3-slim

WORKDIR /usr/src/app

RUN pip3 install pandas==1.1.5 && \
    pip3 install lxml==4.8.0 && \
    pip3 install pymongo==4.0.2
COPY . .

VOLUME ["/usr/src/app/dumps"]


ENTRYPOINT [ "python3", "main.py" ]