from il_supermarket_parsers.engines.base import BaseFileConverter
from .bareket import BareketFileConverter
from .confix import CofixFileConverter
from .mahsani_a_shuk import MahsaniAShukPromoFileConverter
from .salach_dabach import SalachDabachFileConverter
from .shufersal import ShufersalFileConverter
from .super_pharm import SuperPharmFileConverter
from .victory import VictoryFileConverter
from .het_cohen import HetChoenFileConverter
from .tiv_taam import TivTaamFileConverter
from .other import *
