name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on:
      - self-hosted
      - ci

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Free disk space
      run: |
        df --human-readable
        docker 2>/dev/null 1>&2 rmi $(docker image ls --all --quiet) || true
        rm --recursive --force "$AGENT_TOOLSDIRECTORY"
        df --human-readable

    - name: Build with Docker
      run: docker build -t erlichsefi/israeli-supermarket-parsers:lint --target lint .

    - name: Remove legacy pylint container name
      run: docker rm -f parsers-pylint-runner 2>/dev/null || true

    - name: Analysing the code with pylint
      run: |
        mkdir -p temp
        set -o pipefail
        docker run --rm -v ./temp:/usr/src/app/temp --name parsers-pylint-runner erlichsefi/israeli-supermarket-parsers:lint 2>&1 | tee pylint-log.txt

    - name: Docker builder prune
      if: always()
      run: docker builder prune -f
