# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit & Integration Tests


on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '00 19 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
  
jobs:
  build:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.0"]

    steps:

    - name: Checkout
      uses: actions/checkout@v3
    - name: Free disk space
      run: |
        df --human-readable
        sudo apt clean
        docker 2>/dev/null 1>&2 rmi $(docker image ls --all --quiet) || true
        rm --recursive --force "$AGENT_TOOLSDIRECTORY"
        df --human-readable
    - name: Build with Docker
      run: docker build -t erlichsefi/israeli-supermarket-parsers:test --target test .
    - name: Remove all build
      run: (docker stop parsers-test-runner 2>/dev/null || true) && (docker rm parsers-test-runner 2>/dev/null || true)
    - name: Test with pytest
      run: |
           mkdir -p temp &&
           docker run --memory="800m" --cpus="0.75" --rm -v ./temp:/usr/src/app/temp --name parsers-test-runner erlichsefi/israeli-supermarket-parsers:test &&
           docker builder prune -f